#android.aosp.overlay
#android.miui.home.launcher.res
#android.miui.overlay
#android.overlay.common
#android.overlay.target
#android.qvaoverlay.common
#com.android.apps.tag
#com.android.bluetooth.overlay
#com.android.browser
#com.android.camera
#com.android.carrierconfig.overlay.common
#com.android.carrierconfig.overlay.miui
#com.android.cellbroadcastreceiver.overlay.common
#com.android.contacts
#com.android.fileexplorer
#com.android.incallui
#com.android.incallui.overlay
#com.android.inputsettings.overlay.miui
#com.android.mms
#com.android.networkstack.inprocess
#com.android.networkstack.tethering.inprocess
#com.android.overlay.cngmstelecomm
#com.android.overlay.gmscontactprovider
#com.android.overlay.gmssettingprovider
#com.android.overlay.gmssettings
#com.android.overlay.gmstelecomm
#com.android.overlay.gmstelephony
#com.android.overlay.systemui
#com.android.phone.overlay.common
#com.android.providers.settings.overlay
#com.android.provision
#com.android.quicksearchbox
#com.android.remoteprovisioner
#com.android.server.telecom.overlay.common
#com.android.server.telecom.overlay.miui
#com.android.settings.intelligence
#com.android.settings.overlay.common
#com.android.settings.overlay.miui
#com.android.stk.overlay.miui
#com.android.storagemanager
#com.android.systemui.gesture.line.overlay
#com.android.systemui.navigation.bar.overlay
#com.android.systemui.overlay.common
#com.android.systemui.overlay.miui
#com.android.thememanager
#com.android.thememanager.customthemeconfig.config.overlay
#com.android.traceur
#com.android.updater
#com.android.wallpapercropper
#com.android.wifi.resources.overlay.common
#com.android.wifi.resources.overlay.taro
#com.android.wifi.resources.xiaomi
#com.bsp.catchlog
#com.fido.asm
#com.fingerprints.sensortesttool
#com.goodix.gftest
#com.google.android.cellbroadcastreceiver.overlay.miui
#com.google.android.cellbroadcastservice.overlay.miui
#com.google.android.overlay.gmsconfig
#com.google.android.overlay.modules.ext.services
#com.lbe.security.miui
#com.milink.service
#com.miui.accessibility
#com.miui.analytics
#com.miui.aod
#com.miui.audioeffect
#com.miui.audiomonitor
#com.miui.backup
#com.miui.bugreport
#com.miui.carlink
#com.miui.catcherpatch
#com.miui.cit
#com.miui.cloudbackup
#com.miui.cloudconfig
#com.miui.cloudservice
#com.miui.contentcatcher
#com.miui.contentextension
#com.miui.core
#com.miui.core.internal.services
#com.miui.daemon
#com.miui.dmregservice
#com.miui.extraphoto
#com.miui.face
#com.miui.face.overlay.miui
#com.miui.freeform
#com.miui.greenguard
#com.miui.guardprovider
#com.miui.home
#com.miui.hybrid
#com.miui.hybrid.accessory
#com.miui.maintenancemode
#com.miui.mediaviewer
#com.miui.micloudsync
#com.miui.miinput
#com.miui.miservice
#com.miui.mishare.connectivity
#com.miui.misound
#com.miui.miwallpaper
#com.miui.miwallpaper.overlay.customize
#com.miui.nextpay
#com.miui.notification
#com.miui.otaprovision
#com.miui.packageinstaller
#com.miui.personalassistant
#com.miui.phrase
#com.miui.powerkeeper
#com.miui.privacycomputing
#com.miui.qr
#com.miui.rom
#com.miui.screenshot
#com.miui.securityadd
#com.miui.securitycenter
#com.miui.securitycore
#com.miui.securityinputmethod
#com.miui.settings.rro.device.config.overlay
#com.miui.settings.rro.device.hide.statusbar.overlay
#com.miui.settings.rro.device.type.overlay
#com.miui.system
#com.miui.systemAdSolution
#com.miui.system.overlay
#com.miui.systemui.carriers.overlay
#com.miui.systemui.devices.overlay
#com.miui.systemui.overlay.devices.android
#com.miui.touchassistant
#com.miui.translation.kingsoft
#com.miui.translationservice
#com.miui.translation.xmcloud
#com.miui.tsmclient
#com.miui.uireporter
#com.miui.voiceassist
#com.miui.voiceassistoverlay
#com.miui.voicetrigger
#com.miui.vpnsdkmanager
#com.miui.vsimcore
#com.miui.wallpaper.overlay.customize
#com.miui.wmsvc
#com.miuix.editor
#com.miui.yellowpage
#com.mobiletools.systemhelper
#com.modemdebug
#com.qti.dcf
#com.qti.dpmserviceapp
#com.qti.phone
#com.qti.qcc
#com.qti.qualcomm.datastatusnotification
#com.qti.qualcomm.deviceinfo
#com.qti.service.colorservice
#com.qti.snapdragon.qdcm_ff
#com.qualcomm.atfwd
#com.qualcomm.embms
#com.qualcomm.location
#com.qualcomm.qcrilmsgtunnel
#com.qualcomm.qti.autoregistration
#com.qualcomm.qti.cne
#com.qualcomm.qti.confdialer
#com.qualcomm.qti.devicestatisticsservice
#com.qualcomm.qti.dynamicddsservice
#com.qualcomm.qti.gpudrivers.taro.api32
#com.qualcomm.qtil.btdsda
#com.qualcomm.qti.lpa
#com.qualcomm.qti.performancemode
#com.qualcomm.qti.poweroffalarm
#com.qualcomm.qti.powersavemode
#com.qualcomm.qti.qcolor
#com.qualcomm.qti.qms.service.trustzoneaccess
#com.qualcomm.qti.remoteSimlockAuth
#com.qualcomm.qti.ridemodeaudio
#com.qualcomm.qti.server.qtiwifi
#com.qualcomm.qti.telephonyservice
#com.qualcomm.qti.uceShimService
#com.qualcomm.qti.uim
#com.qualcomm.qti.uimGbaApp
#com.qualcomm.qti.workloadclassifier
#com.qualcomm.qti.xrcb
#com.qualcomm.timeservice
#com.qualcomm.uimremoteclient
#com.qualcomm.uimremoteserver
#com.qualcomm.wfd.service
#com.quicinc.voice.activation
#com.rongcard.eidapi
#com.sohu.inputmethod.sogou.xiaomi
#com.tencent.soter.soterserver
#com.unionpay.tsmservice.mi
#com.wapi.wapicertmanage
#com.xiaomi.account
#com.xiaomi.aiasst.service
#com.xiaomi.aiasst.vision
#com.xiaomi.aireco
#com.xiaomi.barrage
#com.xiaomi.bluetooth
#com.xiaomi.bluetooth.rro.device.config.overlay
#com.xiaomi.cameratools
#com.xiaomi.digitalkey
#com.xiaomi.finddevice
#com.xiaomi.gamecenter.sdk.service
#com.xiaomi.gnss.polaris
#com.xiaomi.joyose
#com.xiaomi.location.fused
#com.xiaomi.macro
#com.xiaomi.market
#com.xiaomi.metoknlp
#com.xiaomi.micloud.sdk
#com.xiaomi.mi_connect_service
#com.xiaomi.migameservice
#com.xiaomi.mirror
#com.xiaomi.misettings
#com.xiaomi.mtb
#com.xiaomi.NetworkBoost
#com.xiaomi.otrpbroker
#com.xiaomi.payment
#com.xiaomi.security.onetrack
#com.xiaomi.simactivate.service
#com.xiaomi.touchservice
#com.xiaomi.xmsf
#com.xiaomi.xmsfkeeper
#miui.systemui.plugin
#org.codeaurora.ims
#org.ifaa.aidl.manager
#org.mipay.android.manager
#vendor.qti.hardware.cacert.server
#vendor.qti.imsrcs
#vendor.qti.iwlan
